# Generated by Django 4.0.6 on 2024-01-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktype",
            name="old_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
