# Generated by Django 4.0.6 on 2023-12-05 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklocationdetails',
            name='stock_type',
        ),
        migrations.AddField(
            model_name='stocklocationdetails',
            name='stock_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stocktype'),
        ),
    ]
