# Generated by Django 4.0.6 on 2024-01-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0015_remove_targetlocation_title_and_more'),
        ('stock', '0002_stocktype_old_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockType',
            new_name='StockItemsType',
        ),
    ]
