# Generated by Django 4.0.6 on 2023-11-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0004_alter_project_implementing_partners_and_more"),
        ("stock", "0002_stocktype_cluster"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockreports",
            name="stock_location_details",
        ),
        migrations.CreateModel(
            name="StockReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("stockunits", models.CharField(blank=True, default="", max_length=50, null="")),
                ("qty_in_stock", models.IntegerField(blank=True, default=0, null=True, verbose_name="Qty in Stock")),
                (
                    "qty_in_pipeline",
                    models.IntegerField(blank=True, default=0, null=True, verbose_name="Qty in Pipeline"),
                ),
                ("beneficiary_coverage", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "cluster",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.cluster"
                    ),
                ),
                (
                    "stocktype",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="stock.stocktype"
                    ),
                ),
                (
                    "warehouse_location",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="stock.warehouselocation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Report",
                "verbose_name_plural": "Stock Report",
            },
        ),
        migrations.AddField(
            model_name="stockreports",
            name="stock_report",
            field=models.ManyToManyField(to="stock.stockreport"),
        ),
    ]
