# Generated by Django 4.0.6 on 2024-04-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stockitemstype_old_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreports',
            name='submitted',
        ),
        migrations.AddField(
            model_name='stockreports',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('submitted', 'Submitted')], default='todo', max_length=10),
        ),
    ]
