# Generated by Django 4.0.6 on 2023-11-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0003_remove_stockreports_stock_location_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockreports",
            name="stock_report",
        ),
        migrations.AddField(
            model_name="stockreports",
            name="stock_location_details",
            field=models.ManyToManyField(to="stock.stocklocationdetails"),
        ),
        migrations.DeleteModel(
            name="StockReport",
        ),
    ]
