# Generated by Django 4.0.6 on 2024-04-25 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stockreports_submitted_stockreports_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockreports',
            old_name='status',
            new_name='state',
        ),
    ]
