# Generated by Django 4.0.6 on 2024-01-08 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0003_rename_stocktype_stockitemstype"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockitemstype",
            old_name="stock_items",
            new_name="stock_items_name",
        ),
    ]
