# Generated by Django 4.0.6 on 2024-01-09 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_stock_items_stockitemstype_stock_items_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitemstype',
            old_name='stock_items_name',
            new_name='name',
        ),
    ]
