# Generated by Django 4.0.6 on 2023-11-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0004_alter_project_implementing_partners_and_more"),
        ("stock", "0004_remove_stockreports_stock_report_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stocklocationdetails",
            options={"verbose_name": "Stock Item", "verbose_name_plural": "Stock Item"},
        ),
        migrations.RenameField(
            model_name="stocktype",
            old_name="name",
            new_name="stock_items",
        ),
        migrations.AddField(
            model_name="stocktype",
            name="countries",
            field=models.ManyToManyField(blank=True, to="rh.location"),
        ),
    ]
