# Generated by Django 4.0 on 2024-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stocklocationdetails_people_to_assisted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreports',
            name='stock_location_details',
            field=models.ManyToManyField(to='stock.StockLocationDetails'),
        ),
    ]
