# Generated by Django 5.1 on 2024-11-11 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_alter_targetlocation_facility_monitoring'),
        ('stock', '0005_stocklocationdetails_people_to_assisted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('todo', 'To Do'), ('draft', 'Draft'), ('submitted', 'Submitted')], default='todo', max_length=10)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Stock Report',
                'verbose_name_plural': 'Stock Reports',
            },
        ),
        migrations.RemoveField(
            model_name='stockreports',
            name='stock_location_details',
        ),
        migrations.RemoveField(
            model_name='warehouselocation',
            name='district',
        ),
        migrations.RemoveField(
            model_name='warehouselocation',
            name='province',
        ),
        migrations.CreateModel(
            name='StockReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_purpose', models.CharField(blank=True, choices=[('Prepositioned', 'Prepositioned'), ('Operational', 'Operational')], default='', max_length=255, null=True)),
                ('targeted_groups', models.CharField(blank=True, choices=[('All Population', 'All Population'), ('Conflict Affected', 'Conflict Affected'), ('Natural Disaster', 'natural-disaster'), ('Returnees', 'Returnees')], default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Reserved', 'Reserved')], default='', max_length=255, null=True)),
                ('qty_in_stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty in Stock')),
                ('qty_in_pipeline', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty in Pipeline')),
                ('beneficiary_coverage', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_required', models.IntegerField(blank=True, default=0, null=True, verbose_name='No Unit Required')),
                ('people_to_assisted', models.IntegerField(blank=True, default=0, null=True, verbose_name='No People to be assisted')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.cluster')),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockmonthlyreport')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.project')),
                ('stock_item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockitemstype')),
                ('stock_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.stockunit', verbose_name='Units')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Item',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='rh.location')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.organization')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='province', to='rh.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse Location Plan',
                'verbose_name_plural': 'Warehouse Locations',
            },
        ),
        migrations.AddField(
            model_name='stockmonthlyreport',
            name='warehouse_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.warehouse'),
        ),
        migrations.DeleteModel(
            name='StockLocationDetails',
        ),
        migrations.DeleteModel(
            name='StockReports',
        ),
        migrations.DeleteModel(
            name='WarehouseLocation',
        ),
    ]
