# Generated by Django 5.1 on 2024-11-05 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_alter_targetlocation_facility_monitoring'),
        ('stock', '0005_stocklocationdetails_people_to_assisted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouselocation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.organization'),
        ),
    ]
