# Generated by Django 5.1 on 2024-11-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_warehouselocation_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreports',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
