# Generated by Django 5.1 on 2024-11-07 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_alter_targetlocation_facility_monitoring'),
        ('stock', '0009_alter_stockreports_warehouse_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockLocationDetails',
            new_name='StockReport',
        ),
        migrations.RenameModel(
            old_name='WarehouseLocation',
            new_name='Warehouse',
        ),
        migrations.CreateModel(
            name='StockMonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('todo', 'To Do'), ('submitted', 'Submitted')], default='todo', max_length=10)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('warehouse_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Report',
                'verbose_name_plural': 'Stock Reports',
            },
        ),
        migrations.DeleteModel(
            name='StockReports',
        ),
    ]
