# Generated by Django 5.1 on 2024-11-07 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_rename_stocklocationdetails_stockreport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreport',
            name='warehouse_location',
        ),
        migrations.AddField(
            model_name='stockreport',
            name='monthly_report',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='stock.stockmonthlyreport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stockmonthlyreport',
            name='state',
            field=models.CharField(choices=[('todo', 'To Do'), ('draft', 'Draft'), ('submitted', 'Submitted')], default='todo', max_length=10),
        ),
    ]
