# Generated by Django 5.1 on 2024-11-10 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_stockreport_warehouse_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockreport',
            old_name='stock_type',
            new_name='stock_item_type',
        ),
    ]
