# Generated by Django 5.1 on 2024-11-10 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_alter_targetlocation_facility_monitoring'),
        ('stock', '0013_warehouse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.project'),
        ),
    ]
