# Generated by Django 4.0.6 on 2024-02-27 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityPlanReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_achieved", models.IntegerField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "activity_plan",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="rh.activityplan"
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.indicator"),
                ),
            ],
            options={
                "verbose_name": "Activity Plan Report",
                "verbose_name_plural": "Activity Plan Reports",
            },
        ),
        migrations.CreateModel(
            name="TargetLocationReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("facility_monitoring", models.BooleanField(default=False)),
                ("facility_name", models.CharField(blank=True, max_length=200, null=True)),
                ("facility_id", models.CharField(blank=True, max_length=200, null=True)),
                ("facility_lat", models.CharField(blank=True, max_length=200, null=True)),
                ("facility_long", models.CharField(blank=True, max_length=200, null=True)),
                ("nhs_code", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "activity_plan_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_reports.activityplanreport",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_report_country",
                        to="rh.location",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_report_district",
                        to="rh.location",
                    ),
                ),
                (
                    "facility_site_type",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.facilitysitetype"
                    ),
                ),
                (
                    "location_type",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.locationtype"
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_report_province",
                        to="rh.location",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_report_zones",
                        to="rh.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target Location Report",
                "verbose_name_plural": "Target Location Reports",
            },
        ),
        migrations.CreateModel(
            name="ProjectMonthlyReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("todo", "Todo"),
                            ("pending", "Pending"),
                            ("submit", "Submitted"),
                            ("reject", "Rejected"),
                            ("complete", "Completed"),
                        ],
                        default="todo",
                        max_length=15,
                        null=True,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("report_period", models.DateField(blank=True, null=True)),
                ("report_date", models.DateField(blank=True, null=True)),
                ("report_due_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("submitted_on", models.DateTimeField(blank=True, null=True)),
                ("approved_on", models.DateTimeField(blank=True, null=True)),
                ("rejected_on", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.project"
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Report",
                "verbose_name_plural": "Monthly Reports",
            },
        ),
        migrations.CreateModel(
            name="DisaggregationLocationReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=True)),
                ("target", models.IntegerField(blank=True, default=0, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "disaggregation",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="rh.disaggregation"
                    ),
                ),
                (
                    "target_location_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project_reports.targetlocationreport",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disaggregation Location Report",
                "verbose_name_plural": "Disaggregation Location Reports",
            },
        ),
        migrations.AddField(
            model_name="activityplanreport",
            name="monthly_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project_reports.projectmonthlyreport",
            ),
        ),
        migrations.AddField(
            model_name="activityplanreport",
            name="report_types",
            field=models.ManyToManyField(blank=True, to="rh.reporttype"),
        ),
    ]
