# Generated by Django 4.0.6 on 2023-11-27 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0001_initial"),
        ("project_reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityplanreport",
            name="report_types",
            field=models.ManyToManyField(to="rh.reporttype"),
        ),
        migrations.AlterField(
            model_name="activityplanreport",
            name="indicator",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.indicator"),
        ),
    ]
