# Generated by Django 4.0.6 on 2024-03-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='activityplanreport',
            name='report_types',
            field=models.ManyToManyField(blank=True, to='project_reports.responsetype'),
        ),
    ]
