# Generated by Django 4.0.6 on 2024-02-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disaggregationlocationreport',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='projectmonthlyreport',
            old_name='active',
            new_name='is_active',
        ),
    ]
