# Generated by Django 4.0.6 on 2024-03-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0002_responsetype_alter_activityplanreport_report_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsetype',
            name='code',
        ),
    ]
