# Generated by Django 4.0.6 on 2023-12-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_reports", "0003_alter_activityplanreport_report_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityplanreport",
            name="target_achieved",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
