# Generated by Django 4.0.6 on 2024-03-19 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0002_indicatortypesreport'),
        ('project_reports', '0003_remove_responsetype_code'),
    ]

    operations = [
    ]
