# Generated by Django 4.0.6 on 2024-04-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_location_region_name'),
        ('project_reports', '0003_remove_responsetype_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityplanreport',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.currency'),
        ),
        migrations.AddField(
            model_name='activityplanreport',
            name='grant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.granttype'),
        ),
        migrations.AddField(
            model_name='activityplanreport',
            name='implement_modility_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.implementationmodalitytype'),
        ),
        migrations.AddField(
            model_name='activityplanreport',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.packagetype'),
        ),
        migrations.AddField(
            model_name='activityplanreport',
            name='transfer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.transfercategory'),
        ),
        migrations.AddField(
            model_name='activityplanreport',
            name='transfer_mechanism_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.transfermechanismtype'),
        ),
        migrations.AddField(
            model_name='activityplanreport',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.unittype'),
        ),
    ]
