# Generated by Django 4.0.6 on 2024-05-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_alter_location_options'),
        ('project_reports', '0004_activityplanreport_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetlocationreport',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.targetlocation'),
        ),
    ]
