# Generated by Django 4.0.6 on 2023-12-27 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_merge_20231220_0933'),
        ('project_reports', '0004_activityplanreport_target_achieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityplanreport',
            name='report_types',
            field=models.ManyToManyField(blank=True, to='rh.reporttype'),
        ),
    ]
