# Generated by Django 4.0.6 on 2024-05-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0005_targetlocationreport_target_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetlocationreport',
            name='facility_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetlocationreport',
            name='facility_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
