# Generated by Django 4.0.6 on 2024-02-06 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0024_targetlocation_facility_id_and_more"),
        ("project_reports", "0006_targetlocationreport_facility_site_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetlocationreport",
            name="facility_site_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.facilitysitetype"
            ),
        ),
    ]
