# Generated by Django 4.0.6 on 2024-02-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_reports", "0007_alter_targetlocationreport_facility_site_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetlocationreport",
            name="facility_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="targetlocationreport",
            name="facility_lat",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="targetlocationreport",
            name="facility_long",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="targetlocationreport",
            name="facility_monitoring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="targetlocationreport",
            name="facility_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
