# Generated by Django 4.0.6 on 2024-05-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0008_activityplanreport_implementing_partners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmonthlyreport',
            options={'permissions': [('view_5w_dashboard', 'View 5W dashboard')], 'verbose_name': 'Monthly Report', 'verbose_name_plural': 'Monthly Reports'},
        ),
    ]
