# Generated by Django 4.0.6 on 2024-02-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_reports", "0008_targetlocationreport_facility_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetlocationreport",
            name="nhs_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
