# Generated by Django 4.0.6 on 2024-07-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0009_alter_projectmonthlyreport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregationlocationreport',
            name='target_required',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
