# Generated by Django 5.0.7 on 2024-08-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project_reports",
            "0013_rename_active_disaggregationlocationreport_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="disaggregationlocationreport",
            name="target",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Target Reached"
            ),
        ),
    ]
