# Generated by Django 4.0 on 2024-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0026_alter_activitydomain_clusters_and_more'),
        ('project_reports', '0014_alter_disaggregationlocationreport_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityplanreport',
            name='implementing_partners',
            field=models.ManyToManyField(blank=True, related_name='reporting_implementing_partners', to='rh.Organization'),
        ),
        migrations.AlterField(
            model_name='activityplanreport',
            name='report_types',
            field=models.ManyToManyField(blank=True, to='project_reports.ResponseType'),
        ),
        migrations.AlterField(
            model_name='disaggregationlocationreport',
            name='target_required',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Target Required'),
        ),
    ]
