# Generated by Django 4.0 on 2024-08-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0015_activityplanreport_no_of_transfers_and_more'),
        ('project_reports', '0015_alter_activityplanreport_implementing_partners_and_more'),
    ]

    operations = [
    ]
