# Generated by Django 5.0.7 on 2024-08-28 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0015_activityplanreport_no_of_transfers_and_more'),
        ('rh', '0028_remove_activityplan_total_set_target_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityplanreport',
            old_name='report_types',
            new_name='response_types',
        ),
        migrations.RenameField(
            model_name='disaggregationlocationreport',
            old_name='target',
            new_name='reached',
        ),
        migrations.RenameField(
            model_name='projectmonthlyreport',
            old_name='report_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='projectmonthlyreport',
            old_name='report_due_date',
            new_name='to_date',
        ),
        migrations.RemoveField(
            model_name='activityplanreport',
            name='indicator',
        ),
        migrations.RemoveField(
            model_name='activityplanreport',
            name='target_achieved',
        ),
        migrations.RemoveField(
            model_name='disaggregationlocationreport',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='disaggregationlocationreport',
            name='target_required',
        ),
        migrations.RemoveField(
            model_name='projectmonthlyreport',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='projectmonthlyreport',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='projectmonthlyreport',
            name='report_period',
        ),
        migrations.RemoveField(
            model_name='targetlocationreport',
            name='country',
        ),
        migrations.RemoveField(
            model_name='targetlocationreport',
            name='district',
        ),
        migrations.RemoveField(
            model_name='targetlocationreport',
            name='facility_id',
        ),
        migrations.RemoveField(
            model_name='targetlocationreport',
            name='facility_lat',
        ),
        migrations.RemoveField(
            model_name='targetlocationreport',
            name='facility_long',
        ),
        migrations.RemoveField(
            model_name='targetlocationreport',
            name='facility_monitoring',
        ),
        migrations.RemoveField(
            model_name='targetlocationreport',
            name='facility_name',
        ),
        migrations.RemoveField(
            model_name='targetlocationreport',
            name='facility_site_type',
        ),
        migrations.RemoveField(
            model_name='targetlocationreport',
            name='nhs_code',
        ),
        migrations.RemoveField(
            model_name='targetlocationreport',
            name='province',
        ),
        migrations.RemoveField(
            model_name='targetlocationreport',
            name='zone',
        ),
        migrations.AlterField(
            model_name='activityplanreport',
            name='activity_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.activityplan'),
        ),
        migrations.AlterField(
            model_name='activityplanreport',
            name='monthly_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_reports.projectmonthlyreport'),
        ),
        migrations.AlterField(
            model_name='projectmonthlyreport',
            name='state',
            field=models.CharField(blank=True, choices=[('todo', 'Todo'), ('pending', 'Pending'), ('submited', 'Submitted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('archived', 'Archived')], default='todo', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='targetlocationreport',
            name='activity_plan_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_reports.activityplanreport'),
        ),
        migrations.AlterField(
            model_name='targetlocationreport',
            name='target_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.targetlocation'),
        ),
    ]
