# Generated by Django 5.0.7 on 2024-08-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_reports", "0015_activityplanreport_no_of_transfers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityplanreport",
            name="beneficiary_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("new_beneficiary", "New Beneficiary"),
                    ("existing_beneficiaries", "Existing Beneficiaries"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
