# Generated by Django 5.0.7 on 2024-09-11 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0016_rename_report_types_activityplanreport_response_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplanreport',
            name='modality_retargeting',
        ),
    ]
