# Generated by Django 5.0.7 on 2024-08-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0016_rename_report_types_activityplanreport_response_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityplanreport',
            old_name='response_type',
            new_name='response_types',
        ),
    ]
