# Generated by Django 5.0.7 on 2024-09-12 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0017_remove_activityplanreport_modality_retargeting'),
        ('rh', '0030_alter_activityplan_activity_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterDashboardReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_link', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.cluster')),
            ],
            options={
                'verbose_name': 'Cluster Dashboard Report',
                'verbose_name_plural': 'Cluster Dashboard Reports',
            },
        ),
    ]
