# Generated by Django 5.0.7 on 2024-08-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0017_rename_response_type_activityplanreport_response_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmonthlyreport',
            old_name='report_date',
            new_name='from_date',
        ),
        migrations.RenameField(
            model_name='projectmonthlyreport',
            old_name='report_due_date',
            new_name='to_date',
        ),
        migrations.RemoveField(
            model_name='projectmonthlyreport',
            name='report_period',
        ),
    ]
