# Generated by Django 5.0.7 on 2024-09-16 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0018_remove_activityplanreport_implementing_partners_and_more'),
        ('rh', '0031_alter_targetlocation_facility_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityplanreport',
            name='prev_targeted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.indicator'),
        ),
    ]
