# Generated by Django 5.1 on 2024-11-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0019_activityplanreport_prev_targeted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetlocationreport',
            name='beneficiary_status',
            field=models.CharField(choices=[('new_beneficiary', 'New Beneficiary'), ('existing_beneficiaries', 'Existing Beneficiaries')], default='new_beneficiary', max_length=25),
            preserve_default=False,
        ),
    ]
