# Generated by Django 5.1 on 2024-11-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0020_targetlocationreport_beneficiary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetlocationreport',
            name='beneficiary_status',
            field=models.CharField(max_length=25),
        ),
    ]
