# Generated by Django 5.1 on 2024-12-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0021_alter_targetlocationreport_beneficiary_status'),
        ('rh', '0033_remove_budgetprogress_activity_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplanreport',
            name='beneficiary_status',
        ),
        migrations.RemoveField(
            model_name='activityplanreport',
            name='prev_targeted_by',
        ),
        migrations.RemoveField(
            model_name='activityplanreport',
            name='seasonal_retargeting',
        ),
        migrations.AddField(
            model_name='targetlocationreport',
            name='prev_targeted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.indicator'),
        ),
        migrations.AddField(
            model_name='targetlocationreport',
            name='seasonal_retargeting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetlocationreport',
            name='beneficiary_status',
            field=models.CharField(blank=True, choices=[('new_beneficiary', 'New Beneficiary'), ('existing_beneficiaries', 'Existing Beneficiaries')], max_length=25, null=True),
        ),
    ]
