# Generated by Django 5.1.4 on 2025-01-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0024_remove_targetlocationreport_seasonal_retargeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetlocationreport',
            name='safe_space',
            field=models.BooleanField(default=False),
        ),
    ]
