services:
  rh_django:
    container_name: rh_django
    build:
      context: .
      dockerfile: ./docker/Dockerfile.python
    command: poetry run python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/usr/src/rh/src
    ports:
      - 8000:8000
    depends_on:
      - rh_db
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.local

  rh_npm:
    container_name: rh_npm
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.npm
    volumes:
      - ./src:/usr/src/rh/src
    ports:
      - 5173:5173
    entrypoint: ["make","vite"]

  rh_db:
    container_name: rh_postgres_db
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_DB: rh
      POSTGRES_USER: rh_user
      POSTGRES_PASSWORD: rh_1234
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - dbbackups:/pg_backups

volumes:
  postgresql-data:
    driver: local
  dbbackups:
    name: dbbackups