services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile.prod
    container_name: django
    restart: unless-stopped  
    env_file: .env
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.production
      DEBUG: False
    volumes:
      # - './src:/usr/src/rh'
      - static_volume:/usr/src/rh/src/static-cdn
      - media_volume:/usr/src/rh/src/media

  postgres_db:
    image: postgres:14
    container_name: postgres_db
    restart: unless-stopped 
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5434:5432

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/rh/src/static-cdn
      - media_volume:/usr/src/rh/src/media
      - letsencrypt:/etc/letsencrypt 
      - ./docker/nginx/nginx-entrypoint.sh:/nginx-entrypoint.sh
    entrypoint: ["/bin/sh", "/nginx-entrypoint.sh"]
    depends_on:
      - django
      - certbot
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./docker/certbot-entrypoint.sh:/entrypoint.sh
    env_file:
      - .env
    environment:
      - HTTPS_HOST=${HTTPS_HOST}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    restart: no 

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - node_exporter
    # ports:
    # - 9090:9090

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    volumes:
      - '/:/host:ro'
    # ports:
    #   - 9100:9100 

  grafana:
    image: grafana/grafana
    # environment: 
      # GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "true"
      # GF_AUTH_ANONYMOUS_ENABLED: "true"
      # GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      # GF_AUTH_DISABLE_SIGNOUT_MENU: "true"
      # GF_AUTH_DISABLE_LOGIN_FORM: "true"
      # GF_SECURITY_ADMIN_USER: "demo"
      # GF_SECURITY_ADMIN_PASSWORD: "grafana"
    volumes:
      - ./docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./docker/grafana/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
      - 'grafana_storage:/var/lib/grafana'
    # ports:
    #   - 3000:3000

volumes:
  postgres_data:
    name: postgres_data
  static_volume:
    name: static_volume
  media_volume:
    name: media_volume
  letsencrypt:
  grafana_storage: {}