# Generated by Django 4.0.6 on 2023-11-23 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicator",
            name="currency",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.currency"
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="grant_types",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.granttype"
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="implementation_modility_types",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.implementationmodalitytype"
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="location_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.locationtype"
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="package_types",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.packagetype"
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="transfer_category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.transfercategory"
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="transfer_mechanism_types",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.transfermechanismtype"
            ),
        ),
        migrations.AddField(
            model_name="indicator",
            name="unit_types",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.unittype"
            ),
        ),
    ]
