# Generated by Django 4.0.6 on 2024-02-27 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiarytype',
            name='type',
            field=models.CharField(choices=[('hrp', 'HRP'), ('non-hrp', 'Non-HRP')], max_length=200),
        ),
    ]
