# Generated by Django 4.0.6 on 2023-11-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="classification",
            field=models.CharField(
                blank=True, choices=[("urban", "Urban"), ("rural", "Rural")], default="Rural", max_length=15, null=True
            ),
        ),
        migrations.AlterField(
            model_name="activityplan",
            name="beneficiary_category",
            field=models.CharField(
                blank=True,
                choices=[("disabled", "Persons with Disabilities"), ("non-disabled", "Non-Disabled")],
                default="non-disabled",
                max_length=15,
                null=True,
            ),
        ),
    ]
