# Generated by Django 4.0.6 on 2024-02-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityplan',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='activitytype',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='disaggregationlocation',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='targetlocation',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AlterField(
            model_name='beneficiarytype',
            name='type',
            field=models.CharField(choices=[('hrp', 'HRP'), ('non-hrp', 'Non-HRP')], max_length=200),
        ),
    ]
