# Generated by Django 4.0.6 on 2023-11-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0002_location_classification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="classification",
            field=models.CharField(
                blank=True, choices=[("urban", "Urban"), ("rural", "Rural")], max_length=15, null=True
            ),
        ),
    ]
