# Generated by Django 4.0.6 on 2024-03-17 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_activityplan_currency_activityplan_grant_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetlocation',
            name='facility_site_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.facilitysitetype'),
        ),
    ]
