# Generated by Django 4.0.6 on 2024-03-17 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0002_responsetype_alter_activityplanreport_report_types'),
        ('rh', '0002_activityplan_currency_activityplan_grant_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportType',
        ),
    ]
