# Generated by Django 4.0.6 on 2023-11-26 09:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0002_indicator_currency_indicator_grant_types_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indicator",
            old_name="grant_types",
            new_name="gran_type",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="implementation_modility_types",
            new_name="implement_modility_type",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="package_types",
            new_name="package_type",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="transfer_mechanism_types",
            new_name="transfer_mechanism_type",
        ),
        migrations.RenameField(
            model_name="indicator",
            old_name="unit_types",
            new_name="unit_type",
        ),
    ]
