# Generated by Django 4.0.6 on 2024-03-17 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_alter_targetlocation_facility_site_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportType',
        ),
    ]
