# Generated by Django 4.0.6 on 2023-11-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0003_alter_location_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="implementing_partners",
            field=models.ManyToManyField(blank=True, related_name="implementing_partners", to="rh.organization"),
        ),
        migrations.AlterField(
            model_name="project",
            name="programme_partners",
            field=models.ManyToManyField(blank=True, related_name="programme_partners", to="rh.organization"),
        ),
    ]
