# Generated by Django 4.0.6 on 2023-11-26 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0003_rename_grant_types_indicator_gran_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="indicator",
            old_name="gran_type",
            new_name="grant_type",
        ),
    ]
