# Generated by Django 4.0.6 on 2023-12-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0005_remove_beneficiarytype_is_regular_beneficiary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("National NGO", "National NGO"),
                    ("International NGO", "International NGO"),
                    ("Government", "Government"),
                    ("Business", "Business"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
