# Generated by Django 4.0.6 on 2023-12-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0006_alter_organization_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityplan",
            name="total_target",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
