# Generated by Django 4.0.6 on 2023-12-20 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0007_targetlocation_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetlocation",
            name="classification",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.location"
            ),
        ),
    ]
