# Generated by Django 4.0.6 on 2024-03-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_remove_disaggregation_type_disaggregation_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='region_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
