# Generated by Django 4.0.6 on 2024-04-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_location_region_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['code']},
        ),
        migrations.RemoveField(
            model_name='targetlocation',
            name='classification',
        ),
    ]
