# Generated by Django 4.0.6 on 2024-03-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_location_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetlocation',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_region', to='rh.location'),
        ),
    ]
