# Generated by Django 4.0.6 on 2024-05-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetlocation',
            name='facility_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='targetlocation',
            name='facility_long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
