# Generated by Django 4.0.6 on 2023-12-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_alter_targetlocation_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetlocation',
            name='classification',
            field=models.CharField(blank=True, choices=[('urban', 'Urban'), ('rural', 'Rural')], max_length=15, null=True),
        ),
    ]
