# Generated by Django 4.0.6 on 2024-03-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_targetlocation_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetlocation',
            name='region',
        ),
    ]
