# Generated by Django 4.0.6 on 2023-12-20 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0007_activityplan_total_target"),
        ("rh", "0011_alter_targetlocation_classification"),
    ]

    operations = []
