# Generated by Django 4.0.6 on 2024-05-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_alter_targetlocation_facility_lat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
    ]
