# Generated by Django 4.0.6 on 2024-05-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_alter_location_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='enable_retargeting',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
