# Generated by Django 4.0.6 on 2024-01-03 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0012_merge_20231220_0933"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetlocation",
            name="facility_site_type",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.facilitysitetype"),
        ),
    ]
