# Generated by Django 4.0.6 on 2024-05-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_alter_location_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_gap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_received',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
