# Generated by Django 4.0.6 on 2024-05-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0013_indicator_enable_retargeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
