# Generated by Django 4.0.6 on 2024-05-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0013_indicator_enable_retargeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'permissions': [('activate_deactivate_cluster_users', 'activate/deactivate cluster users')]},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['code'], 'permissions': [('activate_deactivate_user', 'Activate/Deactivate users of organization')]},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('archive_unarchive_project', 'Archive/UnArchive project')]},
        ),
    ]
