# Generated by Django 4.0.6 on 2024-01-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0014_remove_activityplan_title_alter_organization_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="targetlocation",
            name="title",
        ),
        migrations.AlterField(
            model_name="activitydetail",
            name="code",
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name="activitydetail",
            name="name",
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name="activitydomain",
            name="code",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="activitydomain",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="code",
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name="activitytype",
            name="name",
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="code",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="donor",
            name="code",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="code",
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name="indicator",
            name="name",
            field=models.CharField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="code",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="code",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="hrp_code",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
