# Generated by Django 4.0.6 on 2024-05-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityplan',
            name='total_set_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
