# Generated by Django 4.0.6 on 2024-06-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0016_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('archive_unarchive_project', 'Archive/UnArchive project'), ('view_org_projects', "View your organization's projects"), ('view_cluster_projects', 'View your clusters projects'), ('copy_project', 'Can copy project')]},
        ),
        migrations.AddField(
            model_name='activityplan',
            name='total_set_target',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=600),
        ),
    ]
