# Generated by Django 4.0.6 on 2024-06-23 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_alter_project_options_activityplan_total_set_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('archive_unarchive_project', 'Archive/UnArchive project'), ('view_org_projects', "View your organization's projects"), ('export_org_projects', "View your organization's projects"), ('view_cluster_projects', 'View your clusters projects'), ('export_cluster_projects', 'Export your clusters projects'), ('copy_project', 'Can copy project'), ('review_project_activity_plan_review', "Can view a project's activity plan review"), ('submit_project', 'Can submit a project')]},
        ),
    ]
