# Generated by Django 5.0.6 on 2024-07-04 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='targetlocation',
            name='group_by_custom',
        ),
        migrations.RemoveField(
            model_name='targetlocation',
            name='group_by_district',
        ),
        migrations.RemoveField(
            model_name='targetlocation',
            name='group_by_province',
        ),
        migrations.RemoveField(
            model_name='targetlocation',
            name='locations_group_by',
        ),
        migrations.AlterField(
            model_name='beneficiarytype',
            name='country',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='countries',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level': 0}, to='rh.location'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='countries',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level': 0}, to='rh.location'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='countries',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level': 0}, to='rh.location'),
        ),
        migrations.AlterField(
            model_name='targetlocation',
            name='country',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_country', to='rh.location'),
        ),
    ]
