# Generated by Django 5.0.6 on 2024-07-04 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_remove_targetlocation_group_by_custom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaggregationlocation',
            name='disaggregation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.disaggregation'),
        ),
        migrations.AlterField(
            model_name='disaggregationlocation',
            name='target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disaggregationlocation',
            name='target_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.targetlocation'),
        ),
        migrations.AlterUniqueTogether(
            name='disaggregationlocation',
            unique_together={('target_location', 'disaggregation')},
        ),
    ]
