# Generated by Django 4.0.6 on 2024-01-15 10:32

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0019_remove_activityplan_indicators_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityplan",
            name="indicator",
            field=smart_selects.db_fields.ChainedForeignKey(
                auto_choose=True,
                blank=True,
                chained_field="activity_type",
                chained_model_field="activity_type",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.indicator",
            ),
        ),
    ]
