# Generated by Django 5.0.6 on 2024-07-08 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0020_alter_disaggregationlocation_disaggregation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytype',
            name='countries',
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='beneficiary',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'non-hrp'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary', to='rh.beneficiarytype'),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='hrp_beneficiary',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'hrp'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrp_beneficiary', to='rh.beneficiarytype'),
        ),
    ]
