# Generated by Django 5.0.6 on 2024-07-16 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0021_remove_activitytype_countries_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytype',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='active',
        ),
        migrations.RemoveField(
            model_name='disaggregationlocation',
            name='active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_hrp_code',
        ),
        migrations.RemoveField(
            model_name='targetlocation',
            name='active',
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='code',
            field=models.SlugField(max_length=600),
        ),
        migrations.AlterField(
            model_name='activitydomain',
            name='code',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='activity_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.activitydomain'),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='activity_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.activitytype'),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.indicator'),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.project'),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In-progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='code',
            field=models.SlugField(max_length=600, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiarytype',
            name='code',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='beneficiarytype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='code',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='disaggregationlocation',
            name='target',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donor',
            name='code',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='countries',
            field=models.ManyToManyField(limit_choices_to={'level': 0}, to='rh.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='donors',
            field=models.ManyToManyField(blank=True, to='rh.donor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in-progress', 'In-progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='targetlocation',
            name='activity_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.activityplan'),
        ),
        migrations.AlterField(
            model_name='targetlocation',
            name='country',
            field=models.ForeignKey(limit_choices_to={'level': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_country', to='rh.location'),
        ),
        migrations.AlterField(
            model_name='targetlocation',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_province', to='rh.location'),
        ),
        migrations.AlterField(
            model_name='targetlocation',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In-progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='unittype',
            name='code',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
