# Generated by Django 5.0.6 on 2024-07-25 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0022_rename_active_activitytype_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=600, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
