# Generated by Django 4.0.6 on 2024-01-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0022_alter_activityplan_activity_detail_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetlocation",
            name="disaggregations",
            field=models.ManyToManyField(
                related_name="disaggregations", through="rh.DisaggregationLocation", to="rh.disaggregation"
            ),
        ),
    ]
