# Generated by Django 4.0.6 on 2024-02-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0023_targetlocation_disaggregations"),
    ]

    operations = [
        migrations.AddField(
            model_name="targetlocation",
            name="facility_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="targetlocation",
            name="facility_lat",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="targetlocation",
            name="facility_long",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="targetlocation",
            name="facility_monitoring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="targetlocation",
            name="facility_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
