# Generated by Django 5.0.6 on 2024-07-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0023_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytype',
            name='activity_date',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='clusters',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='code_indicator',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='hrp_code',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='ocha_code',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='start_date',
        ),
    ]
