# Generated by Django 5.0.6 on 2024-08-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0024_remove_activitytype_activity_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetlocation",
            name="facility_monitoring",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
