# Generated by Django 5.0.7 on 2024-08-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0024_remove_activitytype_activity_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='has_nhs_code',
        ),
    ]
