# Generated by Django 4.0.6 on 2024-02-07 08:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0024_targetlocation_facility_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="targetlocation",
            name="old_id",
        ),
        migrations.RemoveField(
            model_name="targetlocation",
            name="site_lat",
        ),
        migrations.RemoveField(
            model_name="targetlocation",
            name="site_long",
        ),
        migrations.RemoveField(
            model_name="targetlocation",
            name="site_monitoring",
        ),
        migrations.RemoveField(
            model_name="targetlocation",
            name="site_name",
        ),
    ]
