# Generated by Django 4.0.6 on 2024-02-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0024_indidicatortypes"),
    ]

    operations = [
        migrations.AddField(
            model_name="indidicatortypes",
            name="indicator",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.indicator"
            ),
        ),
    ]
