# Generated by Django 5.0.7 on 2024-08-21 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0025_alter_targetlocation_facility_monitoring"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityplan",
            name="no_of_transfers",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AddField(
            model_name="activityplan",
            name="units",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="activitydomain",
            name="countries",
            field=models.ManyToManyField(
                limit_choices_to={"level": 0}, to="rh.location"
            ),
        ),
        migrations.AlterField(
            model_name="targetlocation",
            name="facility_monitoring",
            field=models.BooleanField(default=False),
        ),
    ]
