# Generated by Django 4.0.6 on 2024-02-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0025_remove_targetlocation_old_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityplan",
            name="facility_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="activityplan",
            name="facility_lat",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="activityplan",
            name="facility_long",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="activityplan",
            name="facility_monitoring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activityplan",
            name="facility_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
