# Generated by Django 4.0 on 2024-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0025_alter_targetlocation_facility_monitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydomain',
            name='clusters',
            field=models.ManyToManyField(to='rh.Cluster'),
        ),
        migrations.AlterField(
            model_name='activitydomain',
            name='countries',
            field=models.ManyToManyField(limit_choices_to={'level': 0}, to='rh.Location'),
        ),
        migrations.AlterField(
            model_name='beneficiarytype',
            name='clusters',
            field=models.ManyToManyField(to='rh.Cluster'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='countries',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level': 0}, to='rh.Location'),
        ),
        migrations.AlterField(
            model_name='disaggregation',
            name='clusters',
            field=models.ManyToManyField(to='rh.Cluster'),
        ),
        migrations.AlterField(
            model_name='disaggregation',
            name='indicators',
            field=models.ManyToManyField(to='rh.Indicator'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='clusters',
            field=models.ManyToManyField(blank=True, to='rh.Cluster'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='countries',
            field=models.ManyToManyField(limit_choices_to={'level': 0}, to='rh.Location'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='activity_types',
            field=models.ManyToManyField(to='rh.ActivityType'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='clusters',
            field=models.ManyToManyField(blank=True, to='rh.Cluster'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='countries',
            field=models.ManyToManyField(blank=True, limit_choices_to={'level': 0}, to='rh.Location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='activity_domains',
            field=models.ManyToManyField(related_name='activity_domains', to='rh.ActivityDomain'),
        ),
        migrations.AlterField(
            model_name='project',
            name='clusters',
            field=models.ManyToManyField(to='rh.Cluster'),
        ),
        migrations.AlterField(
            model_name='project',
            name='donors',
            field=models.ManyToManyField(blank=True, to='rh.Donor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='implementing_partners',
            field=models.ManyToManyField(blank=True, related_name='implementing_partners', to='rh.Organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='programme_partners',
            field=models.ManyToManyField(blank=True, related_name='programme_partners', to='rh.Organization'),
        ),
        migrations.AlterField(
            model_name='targetlocation',
            name='disaggregations',
            field=models.ManyToManyField(related_name='disaggregations', through='rh.DisaggregationLocation', to='rh.Disaggregation'),
        ),
        migrations.AlterField(
            model_name='targetlocation',
            name='facility_monitoring',
            field=models.BooleanField(default=False),
        ),
    ]
