# Generated by Django 4.0.6 on 2024-02-20 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0026_remove_indicator_grant_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="projectIndicatorType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.currency"
                    ),
                ),
                (
                    "grant_type",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.granttype"
                    ),
                ),
                (
                    "implement_modility_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rh.implementationmodalitytype",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.indicator"
                    ),
                ),
                (
                    "package_type",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.packagetype"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.project"
                    ),
                ),
                (
                    "transfer_category",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.transfercategory"
                    ),
                ),
                (
                    "transfer_mechanism_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rh.transfermechanismtype",
                    ),
                ),
                (
                    "unit_type",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.unittype"
                    ),
                ),
            ],
        ),
    ]
