# Generated by Django 4.0.6 on 2024-02-07 08:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0026_activityplan_facility_id_activityplan_facility_lat_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activityplan",
            name="facility_id",
        ),
        migrations.RemoveField(
            model_name="activityplan",
            name="facility_lat",
        ),
        migrations.RemoveField(
            model_name="activityplan",
            name="facility_long",
        ),
        migrations.RemoveField(
            model_name="activityplan",
            name="facility_monitoring",
        ),
        migrations.RemoveField(
            model_name="activityplan",
            name="facility_name",
        ),
    ]
