# Generated by Django 5.0.7 on 2024-08-25 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0027_indicator_no_of_transfers_indicator_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='has_nhs_code',
        ),
        migrations.AlterField(
            model_name='targetlocation',
            name='district',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_district', to='rh.location'),
        ),
        migrations.AlterField(
            model_name='targetlocation',
            name='province',
            field=models.ForeignKey(limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_province', to='rh.location'),
        ),
        migrations.AlterField(
            model_name='targetlocation',
            name='zone',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_zones', to='rh.location'),
        ),
    ]
