# Generated by Django 4.0 on 2024-08-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0026_alter_activitydomain_clusters_and_more'),
        ('rh', '0027_indicator_no_of_transfers_indicator_units'),
    ]

    operations = [
    ]
