# Generated by Django 5.0.7 on 2024-09-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0028_remove_activityplan_total_set_target_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytype',
            name='objective',
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='activity_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rh.activitydetail'),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='activity_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rh.activitydomain'),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='activity_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rh.activitytype'),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rh.indicator'),
        ),
        migrations.DeleteModel(
            name='StrategicObjective',
        ),
    ]
