# Generated by Django 5.0.7 on 2024-08-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0028_remove_cluster_has_nhs_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplan',
            name='total_set_target',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='total_target',
        ),
    ]
