# Generated by Django 4.0.6 on 2024-02-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0028_rename_indidicatortypes_indicatortypes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndicatorTypes',
            new_name='IndicatorType',
        ),
    ]
