# Generated by Django 5.1 on 2024-09-05 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0029_remove_activitytype_objective_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityplan",
            name="activity_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rh.activitydetail",
            ),
        ),
    ]
