# Generated by Django 4.0.6 on 2024-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0029_rename_indicatortypes_indicatortype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicatortype",
            name="indicator",
        ),
        migrations.AddField(
            model_name="indicatortype",
            name="indicator",
            field=models.ManyToManyField(to="rh.indicator"),
        ),
    ]
