# Generated by Django 4.0.6 on 2024-02-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0030_remove_indicatortype_indicator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicatortype",
            name="indicator",
        ),
        migrations.AddField(
            model_name="indicatortype",
            name="indicator",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.indicator"
            ),
        ),
    ]
