# Generated by Django 5.0.7 on 2024-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0030_alter_activityplan_activity_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="targetlocation",
            name="facility_monitoring",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
