# Generated by Django 5.1 on 2024-11-20 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_alter_targetlocation_facility_monitoring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplan',
            name='beneficiary_category',
        ),
    ]
