# Generated by Django 5.1 on 2024-11-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0032_remove_activityplan_beneficiary_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetprogress',
            name='activity_domain',
        ),
        migrations.AddField(
            model_name='budgetprogress',
            name='activity_domains',
            field=models.ManyToManyField(to='rh.activitydomain'),
        ),
    ]
