# Generated by Django 4.0.6 on 2024-02-21 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0032_remove_indicatortype_currency_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indicatortype",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="indicatortype",
            name="name",
        ),
        migrations.RemoveField(
            model_name="indicatortype",
            name="type_name",
        ),
        migrations.RemoveField(
            model_name="indicatortype",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="indicatortype",
            name="amount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=600)),
                (
                    "type_name",
                    models.CharField(
                        blank=True, choices=[("grant", "Grant"), ("package", "Package")], max_length=15, null=True
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                ("clusters", models.ManyToManyField(to="rh.cluster")),
                ("indicators", models.ManyToManyField(to="rh.indicator")),
            ],
        ),
        migrations.AddField(
            model_name="indicator",
            name="types",
            field=models.ManyToManyField(related_name="types", through="rh.IndicatorType", to="rh.type"),
        ),
        migrations.AddField(
            model_name="indicatortype",
            name="type",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="rh.type"),
        ),
    ]
