# Generated by Django 5.1.4 on 2025-01-14 06:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0033_remove_budgetprogress_activity_domain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='implement_modility_type',
            new_name='implement_category',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='grant_type',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='implement_modility_type',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='no_of_transfers',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='transfer_category',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='transfer_mechanism_type',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='units',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='grant_type',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='no_of_transfers',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='transfer_category',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='transfer_mechanism_type',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='units',
        ),
        migrations.AddField(
            model_name='implementationmodalitytype',
            name='type',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('In Kind', 'In Kind')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='indicator',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packagetype',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.unittype'),
        ),
        migrations.AddField(
            model_name='unittype',
            name='modality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.implementationmodalitytype'),
        ),
        migrations.CreateModel(
            name='CashInKindDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(blank=True, default=0, null=True)),
                ('no_of_transfers', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('activity_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.activityplan')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.currency')),
                ('grant_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.granttype')),
                ('implement_modality_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.implementationmodalitytype')),
                ('package_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.packagetype')),
                ('transfer_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.transfercategory')),
                ('transfer_mechanism_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.transfermechanismtype')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.unittype')),
            ],
            options={
                'verbose_name': 'Cash In-Kind Detail',
                'verbose_name_plural': 'Cash In-Kind Details',
            },
        ),
    ]
