# Generated by Django 5.1.4 on 2025-01-16 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rh",
            "0034_rename_implement_modility_type_indicator_implement_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="disaggregationlocation",
            name="disaggregation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.disaggregation",
            ),
        ),
    ]
