# Generated by Django 5.1.4 on 2025-01-19 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0034_rename_implement_modility_type_indicator_implement_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RationSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Ration size',
                'verbose_name_plural': 'Ration sizes',
            },
        ),
        migrations.CreateModel(
            name='RationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Ration Type',
                'verbose_name_plural': 'Ration Types',
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='indicator',
            name='package',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cashinkinddetail',
            name='ration_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.rationsize'),
        ),
        migrations.AddField(
            model_name='cashinkinddetail',
            name='ration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.rationtype'),
        ),
    ]
