# Generated by Django 4.0.6 on 2024-02-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0029_targetlocation_nhs_code'),
        ('rh', '0034_remove_type_clusters_remove_type_indicators_and_more'),
    ]

    operations = [
    ]
