# Generated by Django 5.1.4 on 2025-01-09 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0034_remove_activityplan_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementationmodalitytype',
            name='type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('in-kind', 'In-Kind')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='unittype',
            name='modility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.implementationmodalitytype'),
        ),
    ]
