# Generated by Django 5.1.4 on 2025-01-20 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rh", "0035_rationsize_rationtype_indicator_food_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disaggregationlocation",
            name="disaggregation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rh.disaggregation",
            ),
        ),
    ]
