# Generated by Django 5.1.4 on 2025-01-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0036_transfercategory_modility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='category',
        ),
        migrations.AddField(
            model_name='indicator',
            name='implement_modility',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
