# Generated by Django 5.1.4 on 2025-01-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0037_remove_indicator_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='implement_modility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.implementationmodalitytype'),
        ),
    ]
