# Generated by Django 5.1.4 on 2025-01-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0038_alter_indicator_implement_modility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfermechanismtype',
            old_name='modality',
            new_name='modility',
        ),
    ]
