# Generated by Django 4.0.6 on 2023-04-06 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('activity_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('hrp_code', models.CharField(blank=True, max_length=300, null=True)),
                ('code_indicator', models.BooleanField(blank=True, default=False, null=True)),
                ('code', models.CharField(blank=True, max_length=600, null=True)),
                ('name', models.CharField(blank=True, max_length=600, null=True)),
                ('subdomain_code', models.CharField(blank=True, max_length=600, null=True)),
                ('subdomain_name', models.CharField(blank=True, max_length=600, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('fields', models.JSONField(blank=True, default=dict, null=True)),
                ('old_id', models.CharField(blank=True, max_length=300, null=True)),
                ('ocha_code', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('done', 'Completed'), ('archive', 'Archived')], default='draft', max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('beneficiary_category', models.CharField(blank=True, choices=[('disabled', 'Persons with Disabilities'), ('non-disabled', 'Non-Disabled')], default=False, max_length=15, null=True)),
                ('female_0_5', models.IntegerField(blank=True, null=True)),
                ('female_6_12', models.IntegerField(blank=True, null=True)),
                ('female_12_17', models.IntegerField(blank=True, null=True)),
                ('female_18', models.IntegerField(blank=True, null=True)),
                ('female_total', models.IntegerField(blank=True, null=True)),
                ('male_0_5', models.IntegerField(blank=True, null=True)),
                ('male_6_12', models.IntegerField(blank=True, null=True)),
                ('male_12_17', models.IntegerField(blank=True, null=True)),
                ('male_18', models.IntegerField(blank=True, null=True)),
                ('male_total', models.IntegerField(blank=True, null=True)),
                ('other_0_5', models.IntegerField(blank=True, null=True)),
                ('other_6_12', models.IntegerField(blank=True, null=True)),
                ('other_12_17', models.IntegerField(blank=True, null=True)),
                ('other_18', models.IntegerField(blank=True, null=True)),
                ('other_total', models.IntegerField(blank=True, null=True)),
                ('total_0_5', models.IntegerField(blank=True, null=True)),
                ('total_6_12', models.IntegerField(blank=True, null=True)),
                ('total_12_17', models.IntegerField(blank=True, null=True)),
                ('total_18', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('households', models.IntegerField(blank=True, null=True)),
                ('activity_fields', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.activity')),
            ],
            options={
                'verbose_name': 'Activity Plan',
                'verbose_name_plural': 'Activity Plans',
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_code', models.CharField(blank=True, max_length=300, null=True)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('old_title', models.CharField(blank=True, max_length=300, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('ocha_code', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('old_id', models.CharField(blank=True, max_length=300, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.cluster')),
            ],
            options={
                'verbose_name': 'Donor',
                'verbose_name_plural': 'Donors',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=600, null=True)),
                ('name', models.CharField(blank=True, max_length=600, null=True)),
                ('numerator', models.CharField(blank=True, max_length=300, null=True)),
                ('denominator', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=1200, null=True)),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('original_name', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, choices=[('All', 'ALL'), ('Country', 'Country'), ('Province', 'Province'), ('District', 'District')], default='Country', max_length=15, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('parent', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.location')),
            ],
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('type', models.CharField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('old_id', models.CharField(blank=True, max_length=300, null=True, verbose_name='Old ID')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('done', 'Completed'), ('archive', 'Archived')], default='draft', max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=300)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('budget', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('activities', models.ManyToManyField(to='rh.activity')),
                ('budget_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.currency')),
                ('clusters', models.ManyToManyField(to='rh.cluster')),
                ('donors', models.ManyToManyField(to='rh.donor')),
                ('implementing_partners', models.ManyToManyField(related_name='implementing_partners', to='rh.organization')),
                ('locations', models.ManyToManyField(to='rh.location')),
                ('programme_partners', models.ManyToManyField(related_name='programme_partners', to='rh.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrategicObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategic_objective_name', models.CharField(blank=True, max_length=300, null=True)),
                ('strategic_objective_description', models.CharField(blank=True, max_length=600, null=True)),
                ('output_objective_name', models.CharField(blank=True, max_length=300, null=True)),
                ('sector_objective_name', models.CharField(blank=True, max_length=300, null=True)),
                ('sector_objective_description', models.CharField(blank=True, max_length=600, null=True)),
                ('denominator', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Objective',
                'verbose_name_plural': 'Objectives',
            },
        ),
        migrations.CreateModel(
            name='TargetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('done', 'Completed'), ('archive', 'Archived')], default='draft', max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_country', to='rh.location')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_district', to='rh.location')),
                ('location_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.locationtype')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.project')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_province', to='rh.location')),
            ],
            options={
                'verbose_name': 'Target Location',
                'verbose_name_plural': 'Target Locations',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boys', models.IntegerField(blank=True, null=True)),
                ('girls', models.IntegerField(blank=True, null=True)),
                ('men', models.IntegerField(blank=True, null=True)),
                ('women', models.IntegerField(blank=True, null=True)),
                ('elderly_men', models.IntegerField(blank=True, null=True)),
                ('elderly_women', models.IntegerField(blank=True, null=True)),
                ('households', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('activity_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.activityplan')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.project')),
            ],
        ),
        migrations.AddField(
            model_name='donor',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location'),
        ),
        migrations.CreateModel(
            name='BeneficiaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('code', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('old_id', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location')),
            ],
            options={
                'verbose_name': 'Beneficiary Type',
                'verbose_name_plural': 'Beneficiary Types',
            },
        ),
        migrations.AddField(
            model_name='activityplan',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.beneficiarytype'),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='clusters',
            field=models.ManyToManyField(to='rh.cluster'),
        ),
        migrations.AddField(
            model_name='activity',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.indicator'),
        ),
        migrations.AddField(
            model_name='activity',
            name='locations',
            field=models.ManyToManyField(to='rh.location'),
        ),
        migrations.AddField(
            model_name='activity',
            name='objective_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.strategicobjective'),
        ),
    ]
