# Generated by Django 4.0.6 on 2023-10-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityplan',
            name='female_headed_households',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='households',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='FacilityMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_id', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_lat', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_long', models.CharField(blank=True, max_length=200, null=True)),
                ('facility_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.facilitysitetype')),
            ],
            options={
                'verbose_name': 'Facility',
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.AddField(
            model_name='activitytype',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.facilitymonitoring'),
        ),
    ]
