# Generated by Django 4.0.6 on 2023-06-19 05:54

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplan',
            name='active',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='age_desegregation',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='female_0_5',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='female_12_17',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='female_18',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='female_6_12',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='female_total',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='hrp_beneficiary',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='indicators',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='male_0_5',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='male_12_17',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='male_18',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='male_6_12',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='male_total',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='old_id',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='other_0_5',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='other_12_17',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='other_18',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='other_6_12',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='other_total',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='state',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='title',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='total',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='total_0_5',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='total_12_17',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='total_18',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='total_6_12',
        ),
        migrations.RemoveField(
            model_name='beneficiarytype',
            name='is_hrp_beneficiary',
        ),
        migrations.RemoveField(
            model_name='beneficiarytype',
            name='is_regular_beneficiary',
        ),
        migrations.RemoveField(
            model_name='project',
            name='active',
        ),
        migrations.AddField(
            model_name='activityplan',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='indicator',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='activity_type', chained_model_field='activity_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.indicator'),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location'),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='beneficiarytype',
            name='type',
            field=models.CharField(blank=True, choices=[('hrp', 'HRP'), ('non-hrp', 'Non-HRP')], default='draft', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='activity_details',
            field=models.ManyToManyField(related_name='activity_details', to='rh.activitydetail'),
        ),
        migrations.AddField(
            model_name='project',
            name='activity_types',
            field=models.ManyToManyField(related_name='activity_types', to='rh.activitytype'),
        ),
        migrations.AddField(
            model_name='project',
            name='beneficiaries',
            field=models.ManyToManyField(related_name='beneficiary_types', to='rh.beneficiarytype'),
        ),
        migrations.AddField(
            model_name='project',
            name='indicators',
            field=models.ManyToManyField(related_name='indicators', to='rh.indicator'),
        ),
        migrations.AddField(
            model_name='project',
            name='locations',
            field=models.ManyToManyField(related_name='locations', to='rh.location'),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.organization'),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='countries',
            field=models.ManyToManyField(to='rh.location'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='clusters',
            field=models.ManyToManyField(to='rh.cluster'),
        ),
        migrations.AlterField(
            model_name='donor',
            name='countries',
            field=models.ManyToManyField(to='rh.location'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='clusters',
            field=models.ManyToManyField(to='rh.cluster'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='countries',
            field=models.ManyToManyField(to='rh.location'),
        ),
        migrations.CreateModel(
            name='ActivityPlanDisaggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('activity_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.activityplan')),
                ('disaggregation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.disaggregation')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.location')),
            ],
        ),
    ]
