# Generated by Django 4.0.6 on 2023-05-21 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='country',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='country',
        ),
        migrations.AddField(
            model_name='donor',
            name='clusters',
            field=models.ManyToManyField(blank=True, null=True, to='rh.cluster'),
        ),
        migrations.AddField(
            model_name='donor',
            name='countries',
            field=models.ManyToManyField(blank=True, null=True, to='rh.location'),
        ),
        migrations.AddField(
            model_name='donor',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='clusters',
            field=models.ManyToManyField(blank=True, null=True, to='rh.cluster'),
        ),
        migrations.AddField(
            model_name='organization',
            name='countries',
            field=models.ManyToManyField(blank=True, null=True, to='rh.location'),
        ),
        migrations.CreateModel(
            name='Disaggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('clusters', models.ManyToManyField(to='rh.cluster')),
                ('indicators', models.ManyToManyField(to='rh.indicator')),
            ],
        ),
    ]
