# Generated by Django 4.0.6 on 2022-10-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklocationreport',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
