# Generated by Django 4.0.6 on 2023-04-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityplan',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
