# Generated by Django 4.0.6 on 2023-04-06 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='locations',
        ),
        migrations.AddField(
            model_name='project',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location'),
        ),
        migrations.AddField(
            model_name='project',
            name='districts',
            field=models.ManyToManyField(related_name='districts', to='rh.location'),
        ),
        migrations.AddField(
            model_name='project',
            name='provinces',
            field=models.ManyToManyField(related_name='provinces', to='rh.location'),
        ),
    ]
