# Generated by Django 4.0.6 on 2023-06-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_remove_activityplan_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplandisaggregation',
            name='location',
        ),
    ]
