# Generated by Django 4.0.10 on 2023-06-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_targetlocation_activity_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregation',
            name='target_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.targetlocation'),
        ),
    ]
