# Generated by Django 4.0.6 on 2023-05-04 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_activityplan_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_recieved', models.IntegerField(blank=True, default=0, null=True)),
                ('received_date', models.DateField(auto_now_add=True, null=True)),
                ('activity_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.activitydomain')),
                ('budget_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.currency')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.donor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.project')),
            ],
        ),
    ]
