# Generated by Django 4.0.6 on 2023-04-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_remove_project_locations_project_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_hrp_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='hrp_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_hrp_project',
            field=models.BooleanField(default=False),
        ),
    ]
