# Generated by Django 4.0.6 on 2022-10-14 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_stocklocationreport_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_purpose', models.CharField(blank=True, choices=[('Prepositioned', 'Prepositioned'), ('Operational', 'Operational')], default='', max_length=255, null=True)),
                ('targeted_groups', models.CharField(blank=True, choices=[('All Population', 'All Population'), ('Conflict Affected', 'Conflict Affected'), ('Natural Disaster', 'Natural Disaster'), ('Returnees', 'Returnees')], default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Reserved', 'Reserved')], default='', max_length=255, null=True)),
                ('qty_in_stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty in Stock')),
                ('qty_in_pipeline', models.IntegerField(blank=True, default=0, null=True, verbose_name='Qty in Pipeline')),
                ('beneficiary_coverage', models.IntegerField(blank=True, default=0, null=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.cluster')),
                ('stock_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.stocktype')),
                ('stock_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.stockunit', verbose_name='Units')),
            ],
            options={
                'verbose_name': 'Stock Detail',
                'verbose_name_plural': 'Stock Details',
            },
        ),
        migrations.CreateModel(
            name='StockReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now=True, null=True)),
                ('stock_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.stocklocationdetails')),
                ('warhouse_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.warehouselocation')),
            ],
            options={
                'verbose_name': 'Stock Report',
                'verbose_name_plural': 'Stock Reports',
            },
        ),
        migrations.DeleteModel(
            name='StockLocationReport',
        ),
    ]
