# Generated by Django 4.0.6 on 2023-04-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_alter_activityplan_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityplan',
            name='age_desegregation',
            field=models.BooleanField(default=False),
        ),
    ]
