# Generated by Django 4.0.6 on 2023-05-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_remove_donor_cluster_remove_donor_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='countries',
            field=models.ManyToManyField(blank=True, null=True, to='rh.location'),
        ),
    ]
