# Generated by Django 4.0.6 on 2023-04-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_project_has_hrp_code_project_hrp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='facility_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='facility_lat',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='facility_long',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='facility_monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='facility_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
