# Generated by Django 4.0.6 on 2023-04-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_activityplan_age_desegregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_gap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_received',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
