# Generated by Django 4.0.6 on 2023-05-04 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_projectfinancialreport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectFinancialReport',
            new_name='FinancialReport',
        ),
        migrations.AlterModelOptions(
            name='financialreport',
            options={'verbose_name': 'Financial Report', 'verbose_name_plural': 'Financial Reports'},
        ),
    ]
