# Generated by Django 4.0.6 on 2022-10-14 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_stocklocationdetails_stockreports_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreports',
            name='stock_details',
        ),
        migrations.RemoveField(
            model_name='stockreports',
            name='warhouse_location',
        ),
        migrations.AddField(
            model_name='stocklocationdetails',
            name='warhouse_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.warehouselocation'),
        ),
        migrations.AddField(
            model_name='stockreports',
            name='stock_location_details',
            field=models.ManyToManyField(to='rh.stocklocationdetails'),
        ),
    ]
