# Generated by Django 4.0.6 on 2023-06-19 06:18

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_remove_activityplandisaggregation_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='code',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='denominator',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='numerator',
        ),
        migrations.AddField(
            model_name='indicator',
            name='activity_details',
            field=models.ManyToManyField(to='rh.activitydetail'),
        ),
        migrations.AlterField(
            model_name='activityplan',
            name='indicator',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='activity_detail', chained_model_field='activity_detail', null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.indicator'),
        ),
    ]
