# Generated by Django 4.0.10 on 2023-06-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_disaggregation_target_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaggregation',
            name='target_location',
        ),
        migrations.CreateModel(
            name='DisaggregationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(blank=True, default=0, null=True)),
                ('disaggregation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.disaggregation')),
                ('target_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.targetlocation')),
            ],
        ),
    ]
