# Generated by Django 4.0.6 on 2023-05-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_cluster_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetprogress',
            name='budget_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('AFN', 'AFN')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('AFN', 'AFN')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
