# Generated by Django 4.0.6 on 2023-03-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_alter_activity_activity_date_alter_activity_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='locations',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(verbose_name='start date'),
        ),
    ]
