# Generated by Django 4.0.6 on 2023-06-19 06:24

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_remove_indicator_code_remove_indicator_denominator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitytype',
            name='activity_date',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='code_indicator',
        ),
        migrations.RemoveField(
            model_name='activitytype',
            name='ocha_code',
        ),
        migrations.AlterField(
            model_name='activitydetail',
            name='activity_type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='activity_type', chained_model_field='activity_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.activitytype'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='activity_domain',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='activity_domain', chained_model_field='activity_domain', null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.activitydomain'),
        ),
    ]
