# Generated by Django 4.0.6 on 2022-10-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_remove_stockreports_stock_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreports',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
