# Generated by Django 4.0.6 on 2023-03-29 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_remove_project_locations_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityplan',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.beneficiarytype'),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='beneficiary_category',
            field=models.CharField(blank=True, choices=[('disabled', 'Persons with Disabilities'), ('non-disabled', 'Non-Disabled')], default=False, max_length=15, null=True),
        ),
    ]
