# Generated by Django 4.0.10 on 2023-07-30 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_remove_disaggregation_target_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplan',
            name='age_desegregation',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='female_0_5',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='female_12_17',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='female_18',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='female_6_12',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='female_total',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='households',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='male_0_5',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='male_12_17',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='male_18',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='male_6_12',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='male_total',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='other_0_5',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='other_12_17',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='other_18',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='other_6_12',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='other_total',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='total',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='total_0_5',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='total_12_17',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='total_18',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='total_6_12',
        ),
    ]
