# Generated by Django 4.0.6 on 2023-05-04 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_rename_projectfinancialreport_financialreport_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialReport',
            new_name='BudgetProgress',
        ),
        migrations.AlterModelOptions(
            name='budgetprogress',
            options={'verbose_name': 'Budget Progress', 'verbose_name_plural': 'Budget Progress'},
        ),
    ]
