# Generated by Django 4.0.6 on 2023-04-16 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_project_budget_gap_project_budget_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetlocation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
