# Generated by Django 4.0.6 on 2023-06-19 06:29

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_remove_activitytype_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydetail',
            name='activity_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.activitytype'),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='activity_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.activitydomain'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='activity_details',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='activity_details', chained_model_field='activity_details', to='rh.activitydetail'),
        ),
    ]
