# Generated by Django 4.0.6 on 2023-05-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_rename_financialreport_budgetprogress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetprogress',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
