# Generated by Django 4.0.6 on 2023-03-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_activityplan_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
