# Generated by Django 4.0.6 on 2022-10-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_stockreports_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocklocationdetails',
            old_name='warhouse_location',
            new_name='warehouse_location',
        ),
    ]
