# Generated by Django 4.0.6 on 2023-05-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_budgetprogress_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetprogress',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
