# Generated by Django 4.0.6 on 2023-03-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_activityplan_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityplan',
            old_name='boys',
            new_name='female_0_5',
        ),
        migrations.RenameField(
            model_name='activityplan',
            old_name='elderly_men',
            new_name='female_12_17',
        ),
        migrations.RenameField(
            model_name='activityplan',
            old_name='elderly_women',
            new_name='female_18',
        ),
        migrations.RenameField(
            model_name='activityplan',
            old_name='girls',
            new_name='female_6_12',
        ),
        migrations.RenameField(
            model_name='activityplan',
            old_name='men',
            new_name='female_total',
        ),
        migrations.RenameField(
            model_name='activityplan',
            old_name='women',
            new_name='male_0_5',
        ),
        migrations.AddField(
            model_name='activityplan',
            name='male_12_17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='male_18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='male_6_12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='male_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='other_0_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='other_12_17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='other_18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='other_6_12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='other_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='total_0_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='total_12_17',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='total_18',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='total_6_12',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
