# Generated by Django 4.0.6 on 2023-09-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_alter_targetlocation_activity_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaggregationlocation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
