# Generated by Django 4.0.6 on 2023-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_alter_budgetprogress_received_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetprogress',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
