# Generated by Django 4.0.6 on 2023-03-29 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_locationtype_project_locations_targetlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetlocation',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_district', to='rh.location'),
        ),
    ]
