# Generated by Django 4.0.6 on 2023-06-19 06:40

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_alter_indicator_activity_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='activity_details',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='activity_types', chained_model_field='activity_types', to='rh.activitydetail'),
        ),
    ]
