# Generated by Django 4.0.6 on 2023-03-30 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_alter_targetlocation_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='implementing_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementing_partner', to='rh.organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_partner', to='rh.organization'),
        ),
    ]
