# Generated by Django 4.0.6 on 2023-03-30 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_project_implementing_partner_project_project_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_partner',
        ),
        migrations.AddField(
            model_name='project',
            name='programme_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programme_partner', to='rh.organization'),
        ),
    ]
