# Generated by Django 4.0.6 on 2023-06-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0010_alter_indicator_activity_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='activity_details',
            field=models.ManyToManyField(to='rh.activitydetail'),
        ),
    ]
