# Generated by Django 4.0.6 on 2023-04-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_remove_project_project_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('done', 'Completed')], default='draft', max_length=15, null=True),
        ),
    ]
