# Generated by Django 4.0.6 on 2023-04-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_project_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='activityplan',
            name='state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('done', 'Completed'), ('archive', 'Archived')], default='draft', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='targetlocation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='targetlocation',
            name='state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('done', 'Completed'), ('archive', 'Archived')], default='draft', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('done', 'Completed'), ('archive', 'Archived')], default='draft', max_length=15, null=True),
        ),
    ]
