# Generated by Django 4.0.6 on 2023-06-19 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0012_alter_activityplan_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityplan',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.indicator'),
        ),
    ]
