# Generated by Django 4.0.6 on 2023-06-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0013_alter_activityplan_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityplan',
            name='location',
        ),
        migrations.AddField(
            model_name='activityplandisaggregation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location'),
        ),
    ]
