# Generated by Django 4.0.6 on 2023-06-19 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_remove_activityplan_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPlanLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('households', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPlanLocationDisaggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_category', models.CharField(blank=True, choices=[('disabled', 'Persons with Disabilities'), ('non-disabled', 'Non-Disabled')], default=False, max_length=15, null=True)),
                ('target', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('activity_plan_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.activityplanlocation')),
                ('disaggregation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.disaggregation')),
            ],
        ),
        migrations.RenameField(
            model_name='activityplan',
            old_name='households',
            new_name='total_reach',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='beneficiary_category',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='facility_id',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='facility_lat',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='facility_long',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='facility_monitoring',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='facility_name',
        ),
        migrations.RemoveField(
            model_name='activityplan',
            name='facility_type',
        ),
        migrations.DeleteModel(
            name='ActivityPlanDisaggregation',
        ),
        migrations.AddField(
            model_name='activityplanlocation',
            name='activity_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.activityplan'),
        ),
        migrations.AddField(
            model_name='activityplanlocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location'),
        ),
    ]
