# Generated by Django 4.0.6 on 2024-03-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_remove_granttype_code_and_more'),
        ('users', '0002_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'Country'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location'),
        ),
    ]
