# Generated by Django 4.0.6 on 2024-06-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_email_verified_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_org_users', 'View users of your organization')], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
