# Generated by Django 5.0.6 on 2024-07-16 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0022_rename_active_activitytype_is_active_and_more'),
        ('users', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(blank=True, limit_choices_to={'level': 0}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.location'),
        ),
    ]
