# Generated by Django 4.0 on 2024-08-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0026_alter_activitydomain_clusters_and_more'),
        ('users', '0007_alter_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='clusters',
            field=models.ManyToManyField(to='rh.Cluster'),
        ),
    ]
